services:
  db:
    image: mysql:8.4.0
    container_name: ${JUNCTION_SLUG}-db
    restart: 'unless-stopped'
    user: root
    volumes:
      - ./.db:/var/lib/mysql
      # - ./config/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./:/var/www
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}

  tribe:
    image: ghcr.io/tribe-framework/junction:latest
    container_name: ${JUNCTION_SLUG}-tribe
    restart: 'unless-stopped'
    working_dir: /var/www/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${TRIBE_PORT}:80" # tribe
      - "${JUNCTION_PORT}:81" # junction
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./applications:/var/www/applications
      - ./.env:/var/www/.env
      - ./api:/var/www/api
      - ./config:/var/www/config
      - ./custom:/var/www/custom
      - ./uploads:/var/www/uploads
      - ./config/phpmyadmin/config.inc.php:/var/www/phpmyadmin/config.inc.php

networks:
  default:
    driver: bridge
    name: ${JUNCTION_SLUG}_network
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}
