services:
  db:
    image: mysql:8.4.0
    container_name: $APP_NAME-db
    restart: 'no'
    user: root
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./tribe:/var/www
    ports:
      - "$DOCKER_DB_PORT:3306"
    environment:
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASS
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASS
      - MYSQL_DATABASE=$DATABASE_NAME

  app:
    image: tribeframework/tribe:latest
    container_name: $APP_NAME-tribe
    restart: 'no'
    working_dir: /var/www/
    depends_on:
      - db
    ports:
      - "$APP_PORT:80"
      - "$JUNCTION_PORT:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./tribe/.env:/var/www/.env
      - ./tribe/config:/var/www/config
      - ./tribe/custom:/var/www/custom
      - ./tribe/uploads:/var/www/uploads
